// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/venom.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry_Stream int32

const (
	LogEntry_STREAM_UNSPECIFIED LogEntry_Stream = 0 // Default value.
	LogEntry_STDOUT             LogEntry_Stream = 1 // Standard output.
	LogEntry_STDERR             LogEntry_Stream = 2 // Standard error.
)

// Enum value maps for LogEntry_Stream.
var (
	LogEntry_Stream_name = map[int32]string{
		0: "STREAM_UNSPECIFIED",
		1: "STDOUT",
		2: "STDERR",
	}
	LogEntry_Stream_value = map[string]int32{
		"STREAM_UNSPECIFIED": 0,
		"STDOUT":             1,
		"STDERR":             2,
	}
)

func (x LogEntry_Stream) Enum() *LogEntry_Stream {
	p := new(LogEntry_Stream)
	*p = x
	return p
}

func (x LogEntry_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogEntry_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_api_venom_proto_enumTypes[0].Descriptor()
}

func (LogEntry_Stream) Type() protoreflect.EnumType {
	return &file_api_venom_proto_enumTypes[0]
}

func (x LogEntry_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogEntry_Stream.Descriptor instead.
func (LogEntry_Stream) EnumDescriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{8, 0}
}

type ProcessDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Dir           string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDefinition) Reset() {
	*x = ProcessDefinition{}
	mi := &file_api_venom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDefinition) ProtoMessage() {}

func (x *ProcessDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDefinition.ProtoReflect.Descriptor instead.
func (*ProcessDefinition) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessDefinition) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProcessDefinition) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *ProcessDefinition) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ProcessStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to State:
	//
	//	*ProcessStatus_Exit
	//	*ProcessStatus_Error
	State         isProcessStatus_State `protobuf_oneof:"state"`
	Runtime       *durationpb.Duration  `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStatus) Reset() {
	*x = ProcessStatus{}
	mi := &file_api_venom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatus) ProtoMessage() {}

func (x *ProcessStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatus.ProtoReflect.Descriptor instead.
func (*ProcessStatus) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessStatus) GetState() isProcessStatus_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ProcessStatus) GetExit() uint32 {
	if x != nil {
		if x, ok := x.State.(*ProcessStatus_Exit); ok {
			return x.Exit
		}
	}
	return 0
}

func (x *ProcessStatus) GetError() string {
	if x != nil {
		if x, ok := x.State.(*ProcessStatus_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *ProcessStatus) GetRuntime() *durationpb.Duration {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type isProcessStatus_State interface {
	isProcessStatus_State()
}

type ProcessStatus_Exit struct {
	Exit uint32 `protobuf:"varint,1,opt,name=exit,proto3,oneof"`
}

type ProcessStatus_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ProcessStatus_Exit) isProcessStatus_State() {}

func (*ProcessStatus_Error) isProcessStatus_State() {}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Definition    *ProcessDefinition     `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Status        *ProcessStatus         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_api_venom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessInfo) GetDefinition() *ProcessDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *ProcessInfo) GetStatus() *ProcessStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StartProcessRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Definition *ProcessDefinition     `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	// Types that are valid to be assigned to WaitFor:
	//
	//	*StartProcessRequest_Regex
	//	*StartProcessRequest_Exit
	WaitFor       isStartProcessRequest_WaitFor `protobuf_oneof:"wait_for"`
	WaitTimeout   *durationpb.Duration          `protobuf:"bytes,4,opt,name=wait_timeout,json=waitTimeout,proto3,oneof" json:"wait_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_api_venom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{3}
}

func (x *StartProcessRequest) GetDefinition() *ProcessDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *StartProcessRequest) GetWaitFor() isStartProcessRequest_WaitFor {
	if x != nil {
		return x.WaitFor
	}
	return nil
}

func (x *StartProcessRequest) GetRegex() string {
	if x != nil {
		if x, ok := x.WaitFor.(*StartProcessRequest_Regex); ok {
			return x.Regex
		}
	}
	return ""
}

func (x *StartProcessRequest) GetExit() bool {
	if x != nil {
		if x, ok := x.WaitFor.(*StartProcessRequest_Exit); ok {
			return x.Exit
		}
	}
	return false
}

func (x *StartProcessRequest) GetWaitTimeout() *durationpb.Duration {
	if x != nil {
		return x.WaitTimeout
	}
	return nil
}

type isStartProcessRequest_WaitFor interface {
	isStartProcessRequest_WaitFor()
}

type StartProcessRequest_Regex struct {
	Regex string `protobuf:"bytes,2,opt,name=regex,proto3,oneof"`
}

type StartProcessRequest_Exit struct {
	Exit bool `protobuf:"varint,3,opt,name=exit,proto3,oneof"`
}

func (*StartProcessRequest_Regex) isStartProcessRequest_WaitFor() {}

func (*StartProcessRequest_Exit) isStartProcessRequest_WaitFor() {}

type StartProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Status        *ProcessStatus         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	mi := &file_api_venom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{4}
}

func (x *StartProcessResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartProcessResponse) GetStatus() *ProcessStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StopProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Wait          bool                   `protobuf:"varint,2,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProcessRequest) Reset() {
	*x = StopProcessRequest{}
	mi := &file_api_venom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessRequest) ProtoMessage() {}

func (x *StopProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessRequest.ProtoReflect.Descriptor instead.
func (*StopProcessRequest) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{5}
}

func (x *StopProcessRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopProcessRequest) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

type StopProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        *ProcessStatus         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProcessResponse) Reset() {
	*x = StopProcessResponse{}
	mi := &file_api_venom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessResponse) ProtoMessage() {}

func (x *StopProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessResponse.ProtoReflect.Descriptor instead.
func (*StopProcessResponse) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{6}
}

func (x *StopProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopProcessResponse) GetStatus() *ProcessStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromStart     bool                   `protobuf:"varint,2,opt,name=from_start,json=fromStart,proto3" json:"from_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_api_venom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{7}
}

func (x *StreamLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamLogsRequest) GetFromStart() bool {
	if x != nil {
		return x.FromStart
	}
	return false
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Stream        LogEntry_Stream        `protobuf:"varint,3,opt,name=stream,proto3,enum=venom.LogEntry_Stream" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_venom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogEntry) GetStream() LogEntry_Stream {
	if x != nil {
		return x.Stream
	}
	return LogEntry_STREAM_UNSPECIFIED
}

type ProcessInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Input:
	//
	//	*ProcessInput_Text
	//	*ProcessInput_Data
	Input         isProcessInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInput) Reset() {
	*x = ProcessInput{}
	mi := &file_api_venom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInput) ProtoMessage() {}

func (x *ProcessInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInput.ProtoReflect.Descriptor instead.
func (*ProcessInput) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessInput) GetInput() isProcessInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ProcessInput) GetText() string {
	if x != nil {
		if x, ok := x.Input.(*ProcessInput_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ProcessInput) GetData() []byte {
	if x != nil {
		if x, ok := x.Input.(*ProcessInput_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isProcessInput_Input interface {
	isProcessInput_Input()
}

type ProcessInput_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type ProcessInput_Data struct {
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

func (*ProcessInput_Text) isProcessInput_Input() {}

func (*ProcessInput_Data) isProcessInput_Input() {}

type ListProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_api_venom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{10}
}

func (x *ListProcessesResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,3,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	MemTotal      uint64                 `protobuf:"varint,4,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed       uint64                 `protobuf:"varint,5,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_api_venom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_venom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_venom_proto_rawDescGZIP(), []int{11}
}

func (x *MetricsResponse) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *MetricsResponse) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *MetricsResponse) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *MetricsResponse) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *MetricsResponse) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

var File_api_venom_proto protoreflect.FileDescriptor

const file_api_venom_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/venom.proto\x12\x05venom\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\x11ProcessDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\"{\n" +
	"\rProcessStatus\x12\x14\n" +
	"\x04exit\x18\x01 \x01(\rH\x00R\x04exit\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x123\n" +
	"\aruntime\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\aruntimeB\a\n" +
	"\x05state\"\x85\x01\n" +
	"\vProcessInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\n" +
	"definition\x18\x02 \x01(\v2\x18.venom.ProcessDefinitionR\n" +
	"definition\x12,\n" +
	"\x06status\x18\x03 \x01(\v2\x14.venom.ProcessStatusR\x06status\"\xdd\x01\n" +
	"\x13StartProcessRequest\x128\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\x18.venom.ProcessDefinitionR\n" +
	"definition\x12\x16\n" +
	"\x05regex\x18\x02 \x01(\tH\x00R\x05regex\x12\x14\n" +
	"\x04exit\x18\x03 \x01(\bH\x00R\x04exit\x12A\n" +
	"\fwait_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x01R\vwaitTimeout\x88\x01\x01B\n" +
	"\n" +
	"\bwait_forB\x0f\n" +
	"\r_wait_timeout\"n\n" +
	"\x14StartProcessResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12,\n" +
	"\x06status\x18\x03 \x01(\v2\x14.venom.ProcessStatusR\x06status\"8\n" +
	"\x12StopProcessRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04wait\x18\x02 \x01(\bR\x04wait\"]\n" +
	"\x13StopProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x06status\x18\x02 \x01(\v2\x14.venom.ProcessStatusR\x06status\"B\n" +
	"\x11StreamLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"from_start\x18\x02 \x01(\bR\tfromStart\"\xb4\x01\n" +
	"\bLogEntry\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12.\n" +
	"\x06stream\x18\x03 \x01(\x0e2\x16.venom.LogEntry.StreamR\x06stream\"8\n" +
	"\x06Stream\x12\x16\n" +
	"\x12STREAM_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02\"S\n" +
	"\fProcessInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12\x14\n" +
	"\x04data\x18\x03 \x01(\fH\x00R\x04dataB\a\n" +
	"\x05input\"I\n" +
	"\x15ListProcessesResponse\x120\n" +
	"\tprocesses\x18\x01 \x03(\v2\x12.venom.ProcessInfoR\tprocesses\"\xb7\x01\n" +
	"\x0fMetricsResponse\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x03 \x01(\x01R\n" +
	"memPercent\x12\x1b\n" +
	"\tmem_total\x18\x04 \x01(\x04R\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\x05 \x01(\x04R\amemUsed2\xdc\x02\n" +
	"\vVenomDaemon\x12G\n" +
	"\fStartProcess\x12\x1a.venom.StartProcessRequest\x1a\x1b.venom.StartProcessResponse\x12D\n" +
	"\vStopProcess\x12\x19.venom.StopProcessRequest\x1a\x1a.venom.StopProcessResponse\x12E\n" +
	"\rListProcesses\x12\x16.google.protobuf.Empty\x1a\x1c.venom.ListProcessesResponse\x129\n" +
	"\n" +
	"StreamLogs\x12\x18.venom.StreamLogsRequest\x1a\x0f.venom.LogEntry0\x01\x12<\n" +
	"\n" +
	"GetMetrics\x12\x16.google.protobuf.Empty\x1a\x16.venom.MetricsResponseB)Z'github.com/mathiassmichno/venom/api;apib\x06proto3"

var (
	file_api_venom_proto_rawDescOnce sync.Once
	file_api_venom_proto_rawDescData []byte
)

func file_api_venom_proto_rawDescGZIP() []byte {
	file_api_venom_proto_rawDescOnce.Do(func() {
		file_api_venom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_venom_proto_rawDesc), len(file_api_venom_proto_rawDesc)))
	})
	return file_api_venom_proto_rawDescData
}

var file_api_venom_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_venom_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_venom_proto_goTypes = []any{
	(LogEntry_Stream)(0),          // 0: venom.LogEntry.Stream
	(*ProcessDefinition)(nil),     // 1: venom.ProcessDefinition
	(*ProcessStatus)(nil),         // 2: venom.ProcessStatus
	(*ProcessInfo)(nil),           // 3: venom.ProcessInfo
	(*StartProcessRequest)(nil),   // 4: venom.StartProcessRequest
	(*StartProcessResponse)(nil),  // 5: venom.StartProcessResponse
	(*StopProcessRequest)(nil),    // 6: venom.StopProcessRequest
	(*StopProcessResponse)(nil),   // 7: venom.StopProcessResponse
	(*StreamLogsRequest)(nil),     // 8: venom.StreamLogsRequest
	(*LogEntry)(nil),              // 9: venom.LogEntry
	(*ProcessInput)(nil),          // 10: venom.ProcessInput
	(*ListProcessesResponse)(nil), // 11: venom.ListProcessesResponse
	(*MetricsResponse)(nil),       // 12: venom.MetricsResponse
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_api_venom_proto_depIdxs = []int32{
	13, // 0: venom.ProcessStatus.runtime:type_name -> google.protobuf.Duration
	1,  // 1: venom.ProcessInfo.definition:type_name -> venom.ProcessDefinition
	2,  // 2: venom.ProcessInfo.status:type_name -> venom.ProcessStatus
	1,  // 3: venom.StartProcessRequest.definition:type_name -> venom.ProcessDefinition
	13, // 4: venom.StartProcessRequest.wait_timeout:type_name -> google.protobuf.Duration
	2,  // 5: venom.StartProcessResponse.status:type_name -> venom.ProcessStatus
	2,  // 6: venom.StopProcessResponse.status:type_name -> venom.ProcessStatus
	14, // 7: venom.LogEntry.ts:type_name -> google.protobuf.Timestamp
	0,  // 8: venom.LogEntry.stream:type_name -> venom.LogEntry.Stream
	3,  // 9: venom.ListProcessesResponse.processes:type_name -> venom.ProcessInfo
	14, // 10: venom.MetricsResponse.ts:type_name -> google.protobuf.Timestamp
	4,  // 11: venom.VenomDaemon.StartProcess:input_type -> venom.StartProcessRequest
	6,  // 12: venom.VenomDaemon.StopProcess:input_type -> venom.StopProcessRequest
	15, // 13: venom.VenomDaemon.ListProcesses:input_type -> google.protobuf.Empty
	8,  // 14: venom.VenomDaemon.StreamLogs:input_type -> venom.StreamLogsRequest
	15, // 15: venom.VenomDaemon.GetMetrics:input_type -> google.protobuf.Empty
	5,  // 16: venom.VenomDaemon.StartProcess:output_type -> venom.StartProcessResponse
	7,  // 17: venom.VenomDaemon.StopProcess:output_type -> venom.StopProcessResponse
	11, // 18: venom.VenomDaemon.ListProcesses:output_type -> venom.ListProcessesResponse
	9,  // 19: venom.VenomDaemon.StreamLogs:output_type -> venom.LogEntry
	12, // 20: venom.VenomDaemon.GetMetrics:output_type -> venom.MetricsResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_venom_proto_init() }
func file_api_venom_proto_init() {
	if File_api_venom_proto != nil {
		return
	}
	file_api_venom_proto_msgTypes[1].OneofWrappers = []any{
		(*ProcessStatus_Exit)(nil),
		(*ProcessStatus_Error)(nil),
	}
	file_api_venom_proto_msgTypes[3].OneofWrappers = []any{
		(*StartProcessRequest_Regex)(nil),
		(*StartProcessRequest_Exit)(nil),
	}
	file_api_venom_proto_msgTypes[9].OneofWrappers = []any{
		(*ProcessInput_Text)(nil),
		(*ProcessInput_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_venom_proto_rawDesc), len(file_api_venom_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_venom_proto_goTypes,
		DependencyIndexes: file_api_venom_proto_depIdxs,
		EnumInfos:         file_api_venom_proto_enumTypes,
		MessageInfos:      file_api_venom_proto_msgTypes,
	}.Build()
	File_api_venom_proto = out.File
	file_api_venom_proto_goTypes = nil
	file_api_venom_proto_depIdxs = nil
}
