name: Python

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: cd clients/python && uv sync

      - name: Run linting
        run: make lint

      - name: Run type checking
        run: make typecheck

      - name: Run tests
        run: make test

      - name: Build Python client
        run: make python-client

      - name: Upload Python package
        uses: actions/upload-artifact@v5.0.0
        with:
          name: python-client
          path: clients/python/dist/
