# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import venom_pb2 as venom__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in venom_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class VenomDaemonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartProcess = channel.unary_unary(
            "/venom.VenomDaemon/StartProcess",
            request_serializer=venom__pb2.StartProcessRequest.SerializeToString,
            response_deserializer=venom__pb2.StartProcessResponse.FromString,
            _registered_method=True,
        )
        self.StopProcess = channel.unary_unary(
            "/venom.VenomDaemon/StopProcess",
            request_serializer=venom__pb2.StopProcessRequest.SerializeToString,
            response_deserializer=venom__pb2.StopProcessResponse.FromString,
            _registered_method=True,
        )
        self.SendProcessInput = channel.unary_unary(
            "/venom.VenomDaemon/SendProcessInput",
            request_serializer=venom__pb2.ProcessInput.SerializeToString,
            response_deserializer=venom__pb2.ProcessInputWritten.FromString,
            _registered_method=True,
        )
        self.ListProcesses = channel.unary_unary(
            "/venom.VenomDaemon/ListProcesses",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=venom__pb2.ListProcessesResponse.FromString,
            _registered_method=True,
        )
        self.StreamLogs = channel.unary_stream(
            "/venom.VenomDaemon/StreamLogs",
            request_serializer=venom__pb2.StreamLogsRequest.SerializeToString,
            response_deserializer=venom__pb2.LogEntry.FromString,
            _registered_method=True,
        )
        self.GetMetrics = channel.unary_unary(
            "/venom.VenomDaemon/GetMetrics",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=venom__pb2.MetricsResponse.FromString,
            _registered_method=True,
        )


class VenomDaemonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StopProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendProcessInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListProcesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_VenomDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StartProcess": grpc.unary_unary_rpc_method_handler(
            servicer.StartProcess,
            request_deserializer=venom__pb2.StartProcessRequest.FromString,
            response_serializer=venom__pb2.StartProcessResponse.SerializeToString,
        ),
        "StopProcess": grpc.unary_unary_rpc_method_handler(
            servicer.StopProcess,
            request_deserializer=venom__pb2.StopProcessRequest.FromString,
            response_serializer=venom__pb2.StopProcessResponse.SerializeToString,
        ),
        "SendProcessInput": grpc.unary_unary_rpc_method_handler(
            servicer.SendProcessInput,
            request_deserializer=venom__pb2.ProcessInput.FromString,
            response_serializer=venom__pb2.ProcessInputWritten.SerializeToString,
        ),
        "ListProcesses": grpc.unary_unary_rpc_method_handler(
            servicer.ListProcesses,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=venom__pb2.ListProcessesResponse.SerializeToString,
        ),
        "StreamLogs": grpc.unary_stream_rpc_method_handler(
            servicer.StreamLogs,
            request_deserializer=venom__pb2.StreamLogsRequest.FromString,
            response_serializer=venom__pb2.LogEntry.SerializeToString,
        ),
        "GetMetrics": grpc.unary_unary_rpc_method_handler(
            servicer.GetMetrics,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=venom__pb2.MetricsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "venom.VenomDaemon", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("venom.VenomDaemon", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class VenomDaemon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartProcess(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venom.VenomDaemon/StartProcess",
            venom__pb2.StartProcessRequest.SerializeToString,
            venom__pb2.StartProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StopProcess(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venom.VenomDaemon/StopProcess",
            venom__pb2.StopProcessRequest.SerializeToString,
            venom__pb2.StopProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendProcessInput(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venom.VenomDaemon/SendProcessInput",
            venom__pb2.ProcessInput.SerializeToString,
            venom__pb2.ProcessInputWritten.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListProcesses(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venom.VenomDaemon/ListProcesses",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            venom__pb2.ListProcessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamLogs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/venom.VenomDaemon/StreamLogs",
            venom__pb2.StreamLogsRequest.SerializeToString,
            venom__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venom.VenomDaemon/GetMetrics",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            venom__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
